name = "projektmelody"
compatibility_date = "2024-09-23"
pages_build_output_dir = "public"

[[r2_buckets]]
binding = "R2_VIDEOS"
bucket_name = "r2-videos"

[[r2_buckets]]
binding = "R2_MY_VIDEOS"
bucket_name = "my-videos"

[[r2_buckets]]
binding = "R2_RECENT_VODS"
bucket_name = "recent-vods"

[[r2_buckets]]
binding = "R2_20_VODS"
bucket_name = "20-vods"

[dev]
port = 8788
local_protocol = "http"
