# Interactive helper: paste a direct video URL and print RunPod/docker env to run ingest.
param(
  [string]$Url,
  [string]$Date
)

$ErrorActionPreference = "Stop"
$RepoRoot = Split-Path $PSScriptRoot -Parent
$IngestDir = Join-Path $RepoRoot "runpod\ingest"
$EnvFile = Join-Path $IngestDir ".env.ingest"
$GhcrOwner = "kentangwire"
$Image = "ghcr.io/$GhcrOwner/projektmelody-runpod-ingest:latest"

function Read-Required([string]$Prompt, [string]$Default = "") {
  if ($Default) {
    $line = Read-Host "$Prompt [$Default]"
    if ([string]::IsNullOrWhiteSpace($line)) { return $Default }
    return $line.Trim()
  }
  do {
    $line = (Read-Host $Prompt).Trim()
  } while ([string]::IsNullOrWhiteSpace($line))
  return $line
}

function Get-TitleFromUrl([string]$RawUrl) {
  try {
    $uri = [Uri]$RawUrl
    $name = [IO.Path]::GetFileNameWithoutExtension($uri.LocalPath)
    $name = [Uri]::UnescapeDataString($name)
    if ([string]::IsNullOrWhiteSpace($name)) { return "stream" }
    return $name.Trim()
  } catch {
    return "stream"
  }
}

function Slugify([string]$Text) {
  $s = $Text.ToLower() -replace '[_ ]', '-'
  $s = $s -replace '[^a-z0-9-]', ''
  $s = $s -replace '-{2,}', '-'
  return $s.Trim('-')
}

if (-not $Url) { $Url = Read-Required "Video URL (https://...)" }
if (-not $Date) {
  $Date = Read-Required "Date (YYYY-MM-DD)" (Get-Date -Format "yyyy-MM-dd")
}

if ($Url -notmatch '^(https?)://') {
  Write-Error "URL must start with http:// or https://"
}

$Title = Get-TitleFromUrl $Url
$slug = Slugify $Title
$streamId = "$Date-$slug"
$r2Prefix = "streams/$streamId"

$existing = @{}
if (Test-Path $EnvFile) {
  Get-Content $EnvFile | ForEach-Object {
    if ($_ -match '^\s*([A-Za-z_][A-Za-z0-9_]*)=(.*)$') {
      $existing[$Matches[1]] = $Matches[2]
    }
  }
}

function EnvOrExisting([string]$Key, [string]$Placeholder) {
  if ($existing.ContainsKey($Key) -and $existing[$Key] -and $existing[$Key] -ne $Placeholder) {
    return $existing[$Key]
  }
  return $Placeholder
}

function Format-EnvValue([string]$Value) {
  if ($Value -match '[\s#"$`\\]') {
    $escaped = $Value -replace '\\', '\\' -replace '"', '\"'
    return "`"$escaped`""
  }
  return $Value
}

$envLines = @(
  "# Generated by tools/ingest-url.ps1 — do not commit",
  "URL=$(Format-EnvValue $Url)",
  "DATE=$(Format-EnvValue $Date)",
  "MODE=run",
  "R2_ENDPOINT=$(EnvOrExisting 'R2_ENDPOINT' 'https://YOUR_ACCOUNT_ID.r2.cloudflarestorage.com')",
  "R2_ACCESS_KEY_ID=$(EnvOrExisting 'R2_ACCESS_KEY_ID' 'YOUR_R2_ACCESS_KEY_ID')",
  "R2_SECRET_ACCESS_KEY=$(EnvOrExisting 'R2_SECRET_ACCESS_KEY' 'YOUR_R2_SECRET_ACCESS_KEY')",
  "R2_BUCKET=$(EnvOrExisting 'R2_BUCKET' 'r2-videos')",
  "GITHUB_REPO=$(EnvOrExisting 'GITHUB_REPO' 'kentangwire/projektmelody-archive')",
  "GITHUB_TOKEN=$(EnvOrExisting 'GITHUB_TOKEN' 'YOUR_GITHUB_TOKEN')",
  "WORK_DIR=$(EnvOrExisting 'WORK_DIR' '/work')",
  "IDLE=1"
)

$envLines | Set-Content -Path $EnvFile -Encoding utf8

Write-Host ""
Write-Host "=== Ingest job ===" -ForegroundColor Cyan
Write-Host "Title:      $Title (from filename)"
Write-Host "Stream ID:  $streamId"
Write-Host "R2 prefix:  $r2Prefix"
Write-Host "HLS URL:    /videos/$r2Prefix/master.m3u8"
Write-Host ""
Write-Host "Wrote secrets file: $EnvFile" -ForegroundColor Green
Write-Host "(Fill in R2/GitHub placeholders if this is your first run.)"
Write-Host ""
Write-Host "Pod setup: runpod/ingest/RUNPOD.md (no entrypoint override; image idles on start)" -ForegroundColor DarkGray
Write-Host ""

Write-Host "=== RunPod env (paste into pod UI — secrets only) ===" -ForegroundColor Cyan
@(
  "R2_ENDPOINT=<from .env.ingest>",
  "R2_ACCESS_KEY_ID=<from .env.ingest>",
  "R2_SECRET_ACCESS_KEY=<from .env.ingest>",
  "R2_BUCKET=r2-videos",
  "GITHUB_REPO=kentangwire/projektmelody-archive",
  "GITHUB_TOKEN=<from .env.ingest>",
  "WORK_DIR=/work",
  "IDLE=1",
  "NVIDIA_DRIVER_CAPABILITIES=compute,video,utility",
  "NVIDIA_VISIBLE_DEVICES=all"
) | ForEach-Object { Write-Host $_ }

Write-Host ""
Write-Host "=== On RunPod pod ===" -ForegroundColor Cyan
Write-Host @"
  source $EnvFile   # optional, if copied to the pod
  /app/run-url.sh `"$Url`" `"$Date`"
"@

Write-Host ""
Write-Host "=== Docker run (GPU host with /work volume) ===" -ForegroundColor Cyan
$dockerEnv = @(
  "-e URL=$Url",
  "-e DATE=$Date",
  "-e MODE=run",
  "--env-file $EnvFile"
) -join " "
Write-Host "docker run --rm --gpus all -v /work:/work $dockerEnv $Image"
Write-Host ""
